import Head from 'next/head'

const HomePage = () => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.png' />
    </Head>

    <main>
      <h1>
        Welcome to <a href='https://nextjs.org'>Next.js!</a>
      </h1>
    </main>
  </div>
)

export default HomePage
